language: node_js
node_js:
- 9.11.2
before_script: npm install
script: npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_6eca9b4f4b08_key -iv $encrypted_6eca9b4f4b08_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
  - tar -jcf gcc2ge.tar.bz2 *
  - scp gcc2ge.tar.bz2 ionchain@132.148.155.14:~/