language: go
go_import_path: github.com/gcc2ge/travis_learn
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      go: 1.9.x
      script:
        - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install fuse
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf

    - os: osx
      go: 1.9.x
      sudo: required
      script:
        - brew update
        - brew install caskroom/cask/brew-cask
        - brew cask install osxfuse

script: 
  - make main
  - mv ./build/bin/main ./build/bin/main-$TRAVIS_OS_NAME
deploy:
  provider: releases
  file: "./build/bin/main-$TRAVIS_OS_NAME"
  api_key: ""
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true